export let gameNumbers = [
    {
        int: 1,
        string: "eins"
    }, {
        int: 2,
        string: "zwei"
    }, {
        int: 3,
        string: "drei"
    }, {
        int: 4,
        string: "vier"
    }, {
        int: 5,
        string: "fünf"
    }, {
        int: 6,
        string: "sechs"
    }, {
        int: 7,
        string: "sieben"
    }, {
        int: 8,
        string: "acht"
    }, {
        int: 9,
        string: "neun"
    }, {
        int: 10,
        string: "zehn"
    }, {
        int: 11,
        string: "elf"
    }, {
        int: 12,
        string: "zwölf"
    }, {
        int: 13,
        string: "dreizehn"
    }, {
        int: 14,
        string: "vierzehn"
    }, {
        int: 15,
        string: "fünfzehn"
    }, {
        int: 16,
        string: "sechszehn"
    }, {
        int: 17,
        string: "siebzehn"
    }, {
        int: 18,
        string: "achtzehn"
    }, {
        int: 19,
        string: "neunzehn"
    }, {
        int: 20,
        string: "zwanzig"
    }, {
        int: 21,
        string: "win"
    }
];